### ISSUE TITLE
Error when config is empty

### ISSUE THREAD

**Issue by GoGoris** [johnagan/serverless-parcel#2]
I get errors when custom or custom.parcel.entries are empty in my serverless.yml

> TypeError: entries is not iterable
    at ServerlessPluginParcel.bundle (/Users/steven/projects/aws/serverless-graphql-tutorial/node_modules/serverless-parcel/index.js:48:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From previous event:
    at PluginManager.invoke (/Users/steven/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/lib/classes/PluginManager.js:407:22)
    at PluginManager.spawn (/Users/steven/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/lib/classes/PluginManager.js:425:17)
    at Deploy.BbPromise.bind.then (/Users/steven/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:117:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/Users/steven/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:107:10)
    at BbPromise.reduce (/Users/steven/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/lib/classes/PluginManager.js:407:55)
From previous event:
    at PluginManager.invoke (/Users/steven/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/lib/classes/PluginManager.js:407:22)
    at PluginManager.run (/Users/steven/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/lib/classes/PluginManager.js:438:17)
    at variables.populateService.then.then (/Users/steven/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/lib/Serverless.js:114:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Serverless.run (/Users/steven/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/lib/Serverless.js:101:6)
    at serverless.init.then (/Users/steven/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/bin/serverless:43:28)
    at /Users/steven/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/steven/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at initializeErrorReporter.then (/Users/steven/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/bin/serverless:43:6)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at /Users/steven/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/Users/steven/.nvm/versions/node/v10.15.1/lib/node_modules/serverless/bin/serverless:67:4)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by maxkoryukov** [comment]
I resolved the error by modifying the `serverless.yml` by adding dumb config lines:

```yaml
custom:
  parcel:
    # WORKAROUND:
    entries: []

# -------------------------
# the remaining part is not
# important for this issue
# -------------------------
    # any options
    options:
      bundleNodeModules: true

plugins:
  - serverless-parcel

```
